### ISSUE TITLE
Suggestion: Add import path comment to packages.

### ISSUE THREAD

**Issue by dmitshur** [dominikh/go-unused#1]
You're using a vanity import path, but the packages do not contain `// import "honnef.co/go/unused"` and `// import "honnef.co/go/unused/cmd/unused"` comments enforcing it.

I suggest adding those to prevent people from accidentally starting to use the wrong import paths. You already do this in your other Go packages, for example:
- https://github.com/dominikh/implements/blob/8520c37c175019da1afc816b2be4d9b09c8b4e17/main.go#L1
- https://github.com/dominikh/go-js-dom/blob/24aa052bc5c63cfb9383bf59493ee48621ca788c/dom.go#L109

Feel free to close this issue once you've seen this suggestion, even if you choose not to implement it.

**Comment by dominikh** [comment]
I forgot to add them, thanks.

**Comment by dmitshur** [comment]
You're welcome! :)
