### ISSUE TITLE
Issues building with Go 1.6

### ISSUE THREAD

**Issue by tbayne** [dominikh/go-unused#10]
When attempting to build on OSX and Linux I get a long list of errors that starts with:

`src/honnef.co/go/unused/unused.go:73: impossible type assertion:
        *"go/types".Var does not implement "golang.org/x/tools/go/types".Object (wrong type for Parent method)
                have Parent() *"go/types".Scope
                want Parent() *"golang.org/x/tools/go/types".Scope
src/honnef.co/go/unused/unused.go:78: impossible type assertion:
        *"go/types".TypeName does not implement "golang.org/x/tools/go/types".Object (wrong type for Parent method)
                have Parent() *"go/types".Scope
                want Parent() *"golang.org/x/tools/go/types".Scope`

**Comment by thomshutt** [comment]
Try with `-u`:

`go get -u honnef.co/go/unused/cmd/unused`

**Comment by tbayne** [comment]
That did the trick.  Thank you
