### ISSUE TITLE
Check packages even if some fail to load / don't load all into one huge program

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-unused#14]
Right now, we're loading all packages as one huge program. This is orders of magnitude faster than creating a new program per package, but it causes much higher memory consumption, and refuses to check any packages if one failed to load.

**Comment by cespare** [comment]
Consider chunking into multiple programs by loading a max of N packages together at once?

(Well, you really want some estimate of memory usage. Maybe # of identifiers or something is a better heuristic than # of packages.)

**Comment by jimmyfrasche** [comment]
You could try to load all packages and if that fails fall back to loading them individually, logging any that won't compile.

Failing to load a single package would of course mean that you couldn't do any of the whole-program analysis discussed in #22

**Comment by dominikh** [comment]
A possible solution for checking packages even if some fail to type-check:
1. Construct a dependency graph of all the packages
2. Put all packages that are connected (in the undirected graph) in the same program
3. If that fails to type-check, instead construct programs based on the directed graph.

2 ensures the best runtime (as we won't need to check shared dependencies multiple times) while 3 ensures that we can check the largest amount possible. 

This approach does, however, not solve the issue of memory consumption. Step 2 might still use gigabytes worth of memory. Step 3 could solve that issue (assuming we manage to reclaim the memory. Right now, the way we record data, keeps all programs alive). There could be a cut-off point, a certain number of packages, at which step 2 is skipped and we go straight for step 3. Or we make it a flag. A system with 64 GB of memory wouldn't care for a conservative cut-off point.

**Comment by dominikh** [comment]
Step 2 might not be worth doing as such. Almost any set of packages will be connected by the standard library and we'll end up creating one large program again. Maybe it's worth it when ignoring the standard library in the graph construction. Large systems like juju might still benefit from step 2 and end up with multiple programs that can be checked independently and outweigh the cost of repeatedly checking the standard library (which takes about 6 seconds on my system)

Step 3 does have moderate payoff and manages to reduce the amount of repeated type-checks we need to do. Though whether it's worth the extra complexity is something I have yet to benchmark.

**Comment by dominikh** [comment]
Preliminary benchmarks, running on my GOPATH and GOROOT of 2495 packages in total, some of which don't compile.
1. `./unused all  6498.27s user 746.08s system 510% cpu 23:39.50 total`
2. `( for pkg in $(go list all); do; ./unused $pkg; done; )  6009.99s user 489.08s system 524% cpu 20:38.71 total`

1 uses the graph idea from above. Due to the usage of almost all of the stdlib in GOPATH, it results in one large graph, which doesn't compile. It uses about 4 GB of memory to come to the conclusion that it doesn't compile. It then continues by trying the directed graphs. Most of them, however, consist of only 1-2 packages, making it almost identical to the naive implementation of just trying each package separately.

2 uses a version of the tool without the graph code and instead just spawns one instance of the tool for every package. This naive approach doesn't waste time on trying the huge, broken graph first, and doesn't suffer from any extra complexity.

At this point, it's probably best to just try all packages at once, and if that fails, try each in succession. Trying all at once benefits clean code bases that don't contain broken packages, and the fallback is about as good as it's going to get. And if people are concerned with the peak memory usage, they can use a shell loop instead.
