### ISSUE TITLE
Mark embedded fields as used if they help satisfy interfaces

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-unused#18]
Similarly to methods, fields should be marked as used if they aid in implementing an interface.

**Comment by dmitshur** [comment]
> an interface

Which interface? If you mean any interface, then all methods are used because they aid in implementing some interface created just to make that method used.

**Comment by dominikh** [comment]
See #7, #15 and `testdata/embedding.go` – we already do this to mark methods as used. If an unexported type is embedded in another type and is the reason that the other type implements one of the interfaces (both named and unnamed) defined in the same package, the method is marked as used.

We just need to propagate this information to the anonymous field of the embedding type.
