### ISSUE TITLE
result is nondeterministic

### ISSUE THREAD

**Issue by mhamrle** [dominikh/go-unused#20]
Using go-unused on my large project (about 130 packages) the result is nondeterministic. It returns on of two sets of results.

**Comment by dominikh** [comment]
Is it an open-source project that you can share? And if it isn't, are you at least able to share the two result sets?

**Comment by dominikh** [comment]
FTR, I've seen this behaviour, too, but I cannot reliably reproduce it and even dozens of runs are identical. Only very rarely do I get a different, wrong result, that includes exported identifiers that it shouldn't complain about.

**Comment by mhamrle** [comment]
Unfortunately the project is not open-source so I am not able to share it with you. I had the same symptoms as you described. Please check my fix.
