### ISSUE TITLE
Transitively unused

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-unused#21]
If an identifier `x` is only used by an identifier `y`, and `y` itself is unused, `x` should be marked as unused, too.

We'll have to check if this is worth doing. It'll be faster than having to run the tool several times, but it may increase the memory usage even more.

**Comment by cespare** [comment]
If you decide not to do this (which seems reasonable to me), it would be good to point out in the readme that you'll want to run unused again after deleting code (and repeat until it stops finding things).

**Comment by dominikh** [comment]
Good idea, thanks. I'll add the note to the readme for now and remove it if I end up implementing this.
