### ISSUE TITLE
Check all combinations of GOOS/GOARCH

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-unused#25]
An identifier defined in a file without build tags might be used only in files with specific GOOS/GOARCH (or any other build tag, for that matter) tags. We'll incorrectly flag them as unused unless the tool is run with that same combination of GOOS/GOARCH. 

We could check the package under all combinations, but the naive implementation of that would multiply the runtime by the amount of combinations there are (which are too many.) We could rely on people putting per-arch code in per-arch files only, and "punish" them with false positives if they don't. On the other hand, that punishment might go unnoticed and they might break their code for too long.

Loosely related to https://github.com/dominikh/go-unused/issues/9#issuecomment-197105914

**Comment by dmitshur** [comment]
How will this intersect with potential use of Cgo?

**Comment by dominikh** [comment]
> How will this intersect with potential use of Cgo?

Poorly.

**Comment by dominikh** [comment]
> but the naive implementation of that would multiply the runtime by the amount of combinations there are (which are too many.) 

And to quote concrete numbers for that claim, we can look at the `unconvert` tool, which has an `-all` flag to check all combinations of GOOS/GOARCH:

```
unconvert cmd/go  4.15s user 0.25s system 481% cpu 0.914 total
unconvert -all cmd/go  110.59s user 3.50s system 488% cpu 23.370 total
```

which closely matches the 29 combinations of GOOS/GOARCH that it checks.

**Comment by dmitshur** [comment]
I'm guessing that doesn't even include `js` value for `GOARCH`...

**Comment by dominikh** [comment]
No it does not. However, `js` only adds one more pair, as GOOS is (or should be, in all practical code) irrelevant.

**Comment by jimmyfrasche** [comment]
Testing all combinations would be wasteful most of the time and not cover all the cases. 

The other option would be to parse all the build tags and files with _GOOS or _GOARCH names and compute every set of used builds but that raises a whole host of issues on its own. 

Maybe extend #12 to allow passing a set of build tags to consider and leave it to the user to figure out the minimum set to test?
