### ISSUE TITLE
Find cyclic uses

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-unused#27]
The following program has two functions, which are only used by each other, but never called from the outside. They're effectively unused, but not currently reported.

```
package pkg

func a() {
    b()
}

func b() {
    a()
}
```

**Comment by Deleplace** [comment]
Good catch.

I had noticed the same : http://play.golang.org/p/e0R0Ck6LeH , with some salt because I always fear infinite loops and hypothetical aggressive compilers.
