### ISSUE TITLE
Better cgo support

### ISSUE THREAD

**Issue by jimmyfrasche** [dominikh/go-unused#31]
Checking a package that imports C lists a lot of unused identifiers that are generated by cgo, _Cgo_ptr, _Cgo_always_false, etc. 

The token.Position.Filename for all of these appears to always be C and the identifiers begin with either _c or _C, though I have not checked this very extensively or looked at the cgo source to verify that this always holds. Assuming that it does, perhaps as a special case it could mark those used since there's nothing you could do about it anyway?

**Comment by dominikh** [comment]
There's something we need to do, but your assumptions aren't quite right.

E.g. for the `os/user` package:

```
1:2: field pw_passwd is unused
1:2: field pw_shell is unused
16:6: func _cgo_runtime_cgocallback is unused
22:6: func _cgoCheckResult is unused
/usr/lib/go/src/os/user/C:12:6: func _Cgo_ptr is unused
```

Most don't have a pos.Filename at all, and one isn't just "C" but rooted in the package. Also not all names begin with `_cgo` or `_Cgo_`. If we want to filter those, we'll need to find the correct way of doing so.

**Comment by dominikh** [comment]
I suppose checking for an empty file name or one not ending in ".go" should work well enough, unless we find a better solution.
