### ISSUE TITLE
Detect functions exported to cgo

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-unused#32]
Functions can be marked with an `//export` comment and cgo will use that to allow C world to call these Go functions. This can mean that a Go function is never used by Go and only by C, which we cannot detect. 

We should parse the comment and record the function as a root.

**Comment by petermattis** [comment]
I might be doing something wrong, but this doesn't appear to fix the issue I was seeing on the cockroach code:

```
~/Development/go/src/github.com/cockroachdb/cockroach pmattis/unused unused ./storage/engine/rocksdb
/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb/rocksdb.go:38:6: func rocksDBLog is unused
```

**Comment by dominikh** [comment]
Yeah, I can reproduce the issue. Will investigate.
