### ISSUE TITLE
Ignore generated code

### ISSUE THREAD

**Issue by petermattis** [dominikh/go-unused#33]
Generated code frequently has unused code/variables/constants/etc. For example:

```
~/Development/go/src/github.com/cockroachdb/cockroach pmattis/unused unused ./...
/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/testconfig.pb.go:171:6: func encodeFixed64Testconfig is unused
...
/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/sql/parser/sql.y:254:2: field empty is unused
...
/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/sql/pgwire/clientmessagetype_string.go:17:2: var _clientMessageType_index_2 is unused
```

The above files were generated by `protoc`, `stringer` and `yacc` respectively. All of the generated code has a header comment that says `// Code generated by`. Currently, I just grep to ignore warnings in generated code, but it seems preferable to have this logic builtin to the tool.

**Comment by dominikh** [comment]
I'm partial to looking for "DO NOT EDIT" as opposed to "Code generated by". This ties into https://github.com/golang/go/issues/13560. 

@petermattis, would "DO NOT EDIT" still match all your generated files?

**Comment by dmitshur** [comment]
> would "DO NOT EDIT" still match all your generated files?

According to https://github.com/shurcooL/go/blob/master/analysis/generated_detection.go, which is the best current implementation I could come up with before golang/go#13560 is resolved, just "DO NOT EDIT" on its own is not enough to signal that a file is generated. It should also contain the word "GENERATED" or "generated". Although just "Code generated by" on its own is also enough.

**Comment by dmitshur** [comment]
> just "DO NOT EDIT" on its own is not enough to signal that a file is generated

But maybe it should be?

**Comment by petermattis** [comment]
`DO NOT EDIT` would work for `protoc` and `stringer`, but not for `yacc`. On the other hand, `yacc` doesn't put anything at the top. We currently manually whack in `Code generate by` as that triggers the github auto-generated code detection. We could certainly add something else.

**Comment by dominikh** [comment]
We'll match on `DO NOT EDIT` and `Code generated by`. I would've loved to push my `DO NOT EDIT` agenda, but I'd prefer if you didn't have to edit existing files to work with my tool.

**Comment by cespare** [comment]
Are you just going to check in the header comment? (Or first N bytes / lines?)

**Comment by dominikh** [comment]
> Are you just going to check in the header comment

We're checking the very first comment block in the file. If it turns out that people are putting their copyright notice _before_ that comment (I haven't found anybody do that yet), we'll adjust it to check the first two comment blocks.
