### ISSUE TITLE
Global variable assigned in function and never referenced is not marked as unused

### ISSUE THREAD

**Issue by inconshreveable** [dominikh/go-unused#34]
``` go
package ex

var data int

func init() {
    data = 1
}
```

Expected: unused reports `data` as unused
Observed: false negative

**Comment by cespare** [comment]
I don't think anything here is specific to init.

**Comment by inconshreveable** [comment]
Indeed, you're right, updated the title.

**Comment by dominikh** [comment]
Yes, The current algorithm considers assigned-to variables as used. We do not differentiate between reads and writes. The current data model isn't really designed to represent that information.

I'll see how easy it'll be to extend the data model.

**Comment by dominikh** [comment]
Fixed.
