### ISSUE TITLE
Constants in function bodies are always marked as used

### ISSUE THREAD

**Issue by dsnet** [dominikh/go-unused#35]
Using 16cf7f968ef7ba0cabb3f004ad0679d25077d1a1

Consider the following program:

``` go
package main

import "fmt"

const a = 0 // Unused

func main() {
    const a = 1 // Unused
    {
        const a = 2 // Unused
        {
            const a = 3 // Only this const is used
            fmt.Println(a)
        }
    }
}
```

Currently, `unused` only reports the first const as unused, but in reality, the first 3 const declarations are unused since they are all shadowed by the inner most constant declaration.

**Comment by dominikh** [comment]
This isn't related to shadowing, constants in function bodies aren't checked at all right now:

```
package main

const a = 0

func main() {
    const b = 1
}

/*
$ unused /tmp/foo.go
/tmp/foo.go:3:7: const a is unused
*/
```
