### ISSUE TITLE
No arguments should use .

### ISSUE THREAD

**Issue by mvdan** [dominikh/go-unused#36]
Most linters and all the internal tools use the current package `.` if no arguments are given:

```
$ go fmt
$ go build
$ interfacer
$ golint
$ unused
Usage: unused [flags] [packages]
[...]
```

Any reason why this is so?

Note that `go/loader` doesn't do this for you - in `interfacer` I simply have an early check that replaces `[]` with `["."]`.

**Comment by mvdan** [comment]
You also seem to not vendor `go/loader`. I would strongly suggest you do, as my linter broke twice because of API changes before I started vendoring it.

**Comment by dominikh** [comment]
> Any reason why this is so?

Oversight. Will fix.

> You also seem to not vendor go/loader. I would strongly suggest you do

Generally, I would agree. However, I'm closely following its development, and I prefer breakage and quick fixing over vendoring an old copy, in this case.

**Comment by mvdan** [comment]
> Oversight. Will fix.

I know it's an easy fix, but opened an issue instead of a PR in case it was on purpose.

> Generally, I would agree. However, I'm closely following its development, and I prefer breakage and quick fixing over vendoring an old copy, in this case.

That's actually what I did for months. But once it does break, I had to run to my computer to fix it. And the tool was uninstallable/unusable for at least a few hours.

Instead, I find that vendoring is a much saner approach. About once a week I update the vendored libraries, and I fix any issues that come up. I still closely follow upstream and there never are any updating breakages.

**Comment by dominikh** [comment]
7fb1bdb closes the actual issue (note that we don't need to add any extra code, `gotool.ImportPaths` handles this case for us)

I won't vendor go/loader yet, but I'll keep it on my radar.

**Comment by mvdan** [comment]
I'm confused - I thought gotool wouldn't be needed anymore, and that we should be using `go/*` from the std and `go/loader` alone.

**Comment by dominikh** [comment]
@mvdan There is no package in the standard library that expands patterns like `...` and `std` – There is buildutil.ExpandPatterns, however it doesn't support `...` in arbitrary places, nor does it understand the `std` and `cmd` patterns. Thus we use `gotool`, which is a copy of the Go tool's logic.

golint does something similar, only that they vendored the code from the Go tool instead of relying on gotool.

**Comment by dmitshur** [comment]
`gotool` is still used to convert a list of import path patterns (import paths that may contain "...", or may equal to "std" or "all") into a list of import paths.

E.g., consider running `unused .../cmd/unused go/...`.

**Comment by mvdan** [comment]
I had actually reimplemented (in a terribly buggy way, of course) some of `gotool`. I'm now using it. Thanks for the pointers!
