### ISSUE TITLE
False positive on struct used to parse JSON

### ISSUE THREAD

**Issue by katcipis** [dominikh/go-unused#42]
I have the following struct:

```
type status struct {
    Status *struct {
        Code   *int   `json:"code,omitempty"`
        Detail string `json:"detail,omitempty"`
    } `json:"status,omitempty"`
    Data     map[string]interface{} `json:"data,omitempty"`
    Metadata map[string]interface{} `json:"metadata,omitempty"`
}
```

Which will be used to parse a JSON, change the status.code and re-encode to JSON back:

```
func Convert(inputJson []byte) []byte {
    s := status{}
    if err := json.Unmarshal(inputJson, &s); err != nil {
        return inputJson
    }
    if s.Status == nil || s.Status.Code == nil {
        return inputJson
    }
    *s.Status.Code = convertionMagic(*s.Status.Code)
    output, _ := json.Marshal(s)
    return output
}
```

Im really not sure this is the best way to do it, I cant loose the data/metadata and the status.detail info, so I parse them to make it easier to re-encode them (in the end I really only want to change the status.code).

In this case I got a:

```
Performing static analysis on the code
/go/src/<etc>/status/converter.go:10:3: field Detail is unused
```

But I need Detail there so it can be encoded back again. Not sure if it is a false positive, but I had to disable go-unused on my build because of that :-(

**Comment by dominikh** [comment]
The tool is supposed to handle this case. It's probably getting confused because of the anonymous struct. Will fix.

**Comment by katcipis** [comment]
Thanks @dominikh

**Comment by dominikh** [comment]
Fixed.
