### ISSUE TITLE
testify testsuite test functions marked as unused

### ISSUE THREAD

**Issue by benma** [dominikh/go-unused#43]
Hi

It would be good to be able to specify more functions as root than the default ones. Relevant location, I think, is here:
https://github.com/dominikh/go-unused/blob/9057d575b3bb51f1e1251088a8b8196f4226f936/unused.go#L803

Reason:

I am using [testify](https://github.com/stretchr/testify) to test my code. 

They have [testsuites](https://github.com/stretchr/testify/#suite-package) where methods (not functions) starting with `Test` are run (with the help of reflection, I assume). 

Example from the testify readme:

``` Go
// Basic imports
import (
    "testing"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/suite"
)

// Define the suite, and absorb the built-in basic suite
// functionality from testify - including a T() method which
// returns the current testing context
type ExampleTestSuite struct {
    suite.Suite
    VariableThatShouldStartAtFive int
}

// Make sure that VariableThatShouldStartAtFive is set to five
// before each test
func (suite *ExampleTestSuite) SetupTest() {
    suite.VariableThatShouldStartAtFive = 5
}

// All methods that begin with "Test" are run as tests within a
// suite.
func (suite *ExampleTestSuite) TestExample() {
    assert.Equal(suite.T(), 5, suite.VariableThatShouldStartAtFive)
}

// In order for 'go test' to run this suite, we need to create
// a normal test function and pass our suite to suite.Run
func TestExampleTestSuite(t *testing.T) {
    suite.Run(t, new(ExampleTestSuite))
}
```

All those Test\* methods and all transitively called functions are marked as unused by the tool, even though they are used.

I see three solutions:
1. add a way to configure custom roots (difficult)
2. add a flag "-testify-tests" which, when enabled, adds those methods as roots (extend the isRoot() method). This is the easiest and my preferred solution.
3. Automatically deduce if the method is on a struct that embeds testify's testsuites. This would be the most covenient, but probably overkill in terms of complexity.

If you agree to this change, I can prepare a PR. What are your thoughts?

**Comment by dominikh** [comment]
Option 1 is indeed difficult, and probably not worth the effort. I'm not sure how option 2 and 3 differ, but I'm opposed to adding special handling for testify. If we did that, we'd also need special handling for other testing frameworks. 

I am much more inclined to propose the following solution: Add the following to your test file, for each test:

```
var _ = (*suite)(nil).TestExample
```

**Comment by benma** [comment]
Thanks for the quick response.

I understand that special casing a lib is not great, but if it is hidden behind a flag, all testify users will be made happy.

> If we did that, we'd also need special handling for other testing frameworks. 

If other frameworks suffer the same problem and their solution is as easy, why not? Support can be added on a need-basis, when new issues are created. A good tool should be convenient and integrate well. 

About your proposed workaround: I would not like to clutter all the test files with this, and teach my team to do the same, it would add a significant burden. We write a lot of tests everyday, and adding this for every test would not be welcome.

Please reconsider, it would help a lot. I would also do the coding and contain it so that the testify stuff does not mix with the rest.

**Comment by dominikh** [comment]
> If other frameworks suffer the same problem and their solution is as easy, why not

Because someone (me) has to maintain that code. More code, especially special handling, has the potential to introduce more bugs. It's also code that needs to be adjusted when other parts of the system change. Writing the code itself isn't what introduces the cost.

It might make more sense to maintain a company-internal fork of the tool, with the patches required to make it work as required by the team.

**Comment by benma** [comment]
Hmm, an addition: I just noticed that not all Test\* methods are marked as unused, but only those that are not inside _test.go files. I can work around that maybe, but it's a bit suprising.

**Comment by benma** [comment]
Okay, I understand. Thanks anyway.

**Comment by dominikh** [comment]
> Hmm, an addition: I just noticed that not all Test\* methods are marked as unused, but only those that > are not inside _test.go files. I can work around that maybe, but it's a bit suprising.

Oh yeah, it's quite possible that we currently (incorrectly) ignore Test\* methods in addition to functions. If that's the case, I could be convinced to not fix that bug. And yes, we only ignore tests in _test.go files, as that's where tests should be defined.

**Comment by benma** [comment]
> I could be convinced to not fix that bug.

Yes, please :dancers: 

> as that's where tests should be defined.

I wholeheartedly agree, but unfortunately, there is an edge case where you cannot easily get around defining it outside a _test.go package. If you are interested: if is if you have an interface and multiple implementations, each living in a different package. You want to test all the backends but only write the testing code once (not wrapping each Test*() function in each implementation's _test.go). We're not happy about it but it's the best we could come up with that ensures you don't forget a test in some implementation of the interface.
