### ISSUE TITLE
use more than one tag

### ISSUE THREAD

**Issue by LeoCBS** [dominikh/go-unused#45]
Hi, i am trying use more than one tag in param tags, but seems that when i pass more than one tag, unused don't use any tag and valid all packages

command used:

```
unused -tags=integration,twocaptcha -exported ./...
```

i am using tags correctly?

thanks!

**Comment by dmitshur** [comment]
It's a whitespace-separated list.

Try:

```
unused -tags="integration twocaptcha" -exported ./...
```

**Comment by LeoCBS** [comment]
thanks, work fine with whitespace-separated list
