### ISSUE TITLE
allow whitelisting of types

### ISSUE THREAD

**Issue by tamird** [dominikh/go-unused#48]
In CockroachDB, we have a special type `NoCopy` https://github.com/cockroachdb/cockroach/blob/master/pkg/util/nocopy.go which is never used, but exists to allow `go vet` to catch us in the act of making copies of structures which are not intended to be copied. It would be good to ignore this type without ignoring every file in which it is used.

**Comment by dominikh** [comment]
We might special case the "no copy" kind of type for now. That will require no UI changes and matches a vet check. Any empty struct with an empty Lock method and no other methods will be unlikely to cause false positives.

**Comment by tamird** [comment]
Seems subtle, but I'm OK with it if you are. Also, I assume you mean false negatives.

**Comment by dominikh** [comment]
Well, in the overall context yes, false negatives. Accidentally matching a type as a "no copy" type, at any rate.

**Comment by dominikh** [comment]
Issue has been migrated to https://github.com/dominikh/go-tools/issues/214
