### ISSUE TITLE
Ignore test files

### ISSUE THREAD

**Issue by bradfitz** [dominikh/go-unused#53]
I'm trying to delete a bunch of stuff from a package and iteratively using `unused` to figure out what else to delete as I go.

Unfortunately the tests files contain references to things I want to delete.

I tried to use the `-ignore` flag, documented as:

```
  -ignore string
        Space separated list of checks to ignore, in the following format: 'import/path/file.go:Check1,Check2,...' Both the import path and file name sections support globbing, e.g. 'os/exec/*_test.go'
```

But when I gave an argument of `"*_test.go"` it complained about syntax. I guess I don't know what `Check1,Check2` should be.

My current workaround is to move away all *_test.go files and run unused, delete stuff, then move the test files back, then make the tests pass by fixing or deleting affected tests.

Could there be some sort of `-ignore_tests` flag? Or what syntax am I looking for with `-ignore`?

Thanks!

**Comment by dominikh** [comment]
Try the following for `-ignore`: `-ignore github.com/example/foo/*_test.go:*` – That should ignore all checks for all test files in that package. It's currently mandatory to specify import paths, so just `*_test.go:*` won't work.

**Comment by dominikh** [comment]
Well, that answers the generic question of how the flag works. It will, however, not at all help you here. The ignore flag disables output for specific files and specific checks (think the various checks in staticcheck; unused only has the one check.) – It won't ignore objects in those files. I'll see about adding a way to ignore tests, this seems to be a common enough request.

**Comment by dominikh** [comment]
@bradfitz Done. Use `-tests=false` to skip tests.

**Comment by bradfitz** [comment]
Works great, thanks!!
