### ISSUE TITLE
methods are called funcs

### ISSUE THREAD

**Issue by bradfitz** [dominikh/go-unused#54]
Super minor, but gave me a second pause:

```
foo.go:40:25: func X is unused (U1000)
```

It was actually `method T.X` that was unused.

**Comment by dominikh** [comment]
Given this code

```
type T struct{}
func (T) foo()  {}
func (*T) bar() {}
func foo()      {}
```

would this output cause you to pause, too?

```
foo.go:5:10: func T.foo is unused (U1000)
foo.go:6:11: func (*T).bar is unused (U1000)
foo.go:7:6: func foo is unused (U1000)
```

**Comment by bradfitz** [comment]
No, that would be clear.

I saw "func X" in unused's output and searched for "func X" in emacs (I was already in that file's buffer) and when it didn't find it, I assumed I was running things against the wrong branch.

But if I saw "func (*T).bar", I would know it's a method.

**Comment by bradfitz** [comment]
(And yes, if I had Emacs configured properly I would've just jumped to that position from the `file:line:col` prefix... but I didn't, because I'm both terrible at Emacs, and because I'd just go-got the unused tool)
