### ISSUE TITLE
unused reports exponentialbackoff.delay is unused

### ISSUE THREAD

**Issue by davecheney** [dominikh/go-unused#7]
Sorry that there isn't a shorter repro, the example comes from the juju codebase

```
 go get github.com/juju/juju/worker/storageprovisioner

 % unused . | grep schedule 
 /home/dfc/src/github.com/juju/juju/worker/storageprovisioner/schedule.go:55:30: delay is unused
```

However it is not, the type implements the storageOp interface, so delay cannot be removed.

**Comment by dominikh** [comment]
I see the issue. `exponentialBackoff` does not implement `scheduleOp`, because it's missing the `key` method. I assume `exponentialBackoff` is meant to be embedded in another type that does provide a `key` method? Yeah, we don't currently consider that. I'll add a check for this sort of thing.

**Comment by davecheney** [comment]
Yes, it turns out it is embedded in another type to complete the interface.

**Comment by dominikh** [comment]
This is fixed now.

**Comment by davecheney** [comment]
Thank. Unused culled another 1200 lines of code from juju today.
