### ISSUE TITLE
Type method false positive.

### ISSUE THREAD

**Issue by cznic** [dominikh/go-unused#8]
```
$ unused github.com/cznic/cc
...
/home/jnml/src/github.com/cznic/cc/ast.go:28:30: fragment is unused
...
$
```

[ast.go:28](https://github.com/cznic/cc/blob/c36d47f6f4c66ccd6ac744a7f2ad0ddf42c96a5e/ast.go#L28) is

``` go
func (n *AbstractDeclarator) fragment() interface{} { return n }
```

This method _is_ used [here](https://github.com/cznic/cc/blob/c36d47f6f4c66ccd6ac744a7f2ad0ddf42c96a5e/lexer.go#L397)

``` go
// Reduced implements yyLexerEx
func (l *lexer) Reduced(rule, state int, lval *yySymType) (stop bool) {
    if n := l.exampleRule; n >= 0 && rule != n {
        return false
    }

    switch x := lval.node.(type) {
    case interface {
        fragment() interface{}
    }:
        l.example = x.fragment()
    default:
        l.example = x
    }
    return true
}
```

It's pretty much a corner case, admitted, but perhaps you might want to know about it.

**Comment by dominikh** [comment]
> It's pretty much a corner case, admitted, but perhaps you might want to know about it.

@cznic Please do report any false positives and corner cases you can find. Usually, corner cases reveal some flawed assumption.
