### ISSUE TITLE
Report functions from non-test files that are used only in tests

### ISSUE THREAD

**Issue by kostya-sh** [dominikh/go-unused#9]
This is just an idea of possible useful functionality that can be added to go-unused.

Functions that are used only in the tests should be in `xxx_test.go` files. E.g.: https://github.com/golang/go/commit/6dfcc336c520efc85c5aab06ea9d6c45d0aad214

**Comment by tamird** [comment]
Note that this is not strictly correct - a function may be used from `xx_test.go` in a different package from the one in which it is defined.

**Comment by dominikh** [comment]
@tamird Can you provide an example? An unexported function `fn` in package `foo` can only be used from `foo` and `foo`'s tests, not `bar` or `foo_test`.

**Comment by tamird** [comment]
Ah, I didn't realize that analysis was already scoped to unexported functions. My comment only applies to exported functions, so probably OK to disregard.

**Comment by kostya-sh** [comment]
This idea can be generalized to all build constraints (build tags and GOOS/GOARCH-suffixed files).

For example if an unexported function is used only from `source_windows_amd64.go` then it should be defined in a file with `_windows_amd64.go` suffix.

**Comment by dominikh** [comment]
@kostya-sh See https://github.com/dominikh/go-unused/issues/25 why this isn't really feasible from a performance point of view.
